# Generated by Django 3.2.12 on 2022-05-24 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=300)),
                ('overview', models.CharField(max_length=200)),
                ('popularity', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('release_date', models.CharField(max_length=20)),
                ('genre', models.ManyToManyField(related_name='movie_genre', to='movies.Genre')),
                ('like_users', models.ManyToManyField(related_name='movie_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
